#!/usr/bin/env node
/**
 * Regenerate pricingPreview.js from project-estimator/src/data/pricing.js
 * Run from client-landing: node scripts/sync-pricing.mjs
 */
import { readFileSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const __dirname = dirname(fileURLToPath(import.meta.url))
const pricingPath = join(
  __dirname,
  '..',
  '..',
  'project-estimator',
  'src',
  'data',
  'pricing.js'
)
const outPath = join(__dirname, '..', 'src', 'data', 'pricingPreview.js')

const mod = await import(pricingPath)
const { projectTypes, addOns } = mod

const descById = {
  landing: {
    descEn:
      'High-converting one-pager for product launches, waitlists, or campaigns.',
    descZh: '产品发布、活动或 waitlist 的高转化单页。',
  },
  website: {
    descEn:
      'Multi-section marketing site with services, portfolio, and contact.',
    descZh: '多区块营销站：服务、作品、联系与基础 SEO。',
  },
  dashboard: {
    descEn: 'React UI for SaaS dashboards, admin panels, or data-heavy tools.',
    descZh: 'SaaS 看板、管理后台或数据密集型 React 界面。',
  },
}

const fmtUsd = (n) =>
  `$${n.toLocaleString('en-US', { maximumFractionDigits: 0 })}`

const pricingTiers = projectTypes.map((t) => ({
  id: t.id,
  titleEn: t.labelEn,
  titleZh: t.labelZh,
  range: `${fmtUsd(t.min)} – ${fmtUsd(t.max)}`,
  timelineEn: t.timelineEn.replace(/^Typical timeline:\s*/i, ''),
  timelineZh: t.timelineZh.replace(/^常见周期：约?\s*/i, ''),
  descEn: descById[t.id]?.descEn ?? '',
  descZh: descById[t.id]?.descZh ?? '',
}))

const addOnsPreview = addOns.map((a) => ({
  labelEn: a.labelEn.split('(')[0].trim(),
  labelZh: a.labelZh.split('（')[0].trim(),
  noteEn: `+${a.percent}% on base`,
  noteZh: `基础价 +${a.percent}%`,
}))

const body = `/** Auto-generated by scripts/sync-pricing.mjs — do not edit by hand. */
export const pricingTiers = ${JSON.stringify(pricingTiers, null, 2)}

export const addOnsPreview = ${JSON.stringify(addOnsPreview, null, 2)}
`

writeFileSync(outPath, body, 'utf8')
console.log('Wrote', outPath)
